### ISSUE TITLE
authentication with the device failed

### ISSUE THREAD

**Issue by Isusami** [ExMacro/hass_ensto_ble#11]
Hi
First of all, thanks for the integration.
when I want to add my device when it's on the pairing mode, I select it on HA and select the currency, and after that, I faced with
```
Hass Ensto BLE
Connection and authentication with the device failed. Please try again.

```
From logs:
```
This error originated from a custom integration.
Logger: custom_components.hass_ensto_ble.ensto_thermostat_manager
Source: custom_components/hass_ensto_ble/ensto_thermostat_manager.py:137
integration: Hass Ensto BLE ([documentation](https://github.com/ExMacro/hass_ensto_ble), [issues](https://github.com/ExMacro/hass_ensto_ble/issues))
First occurred: 6:37:08 PM (3 occurrences)
Last logged: 6:49:22 PM

Failed to connect:
Failed to connect: failed to discover services, device disconnected
Failed to connect: [org.bluez.Error.AuthenticationCanceled] Authentication Canceled
```

- I reset the device before
- removed device from any phone and app

I have ECO16BT-J

I use HA in the docker.

**Comment by ExMacro** [comment]
Hi!

Thanks for reporting this.

Did you try multiple times with pairing or just once? The ECO16BT seems to be the more "easy one" from the Ensto selection of thermostats though. The other thermostats seems to fail the connection every now and then for no apparent reason.

In my tests the ECO16BT pairs pretty nicely each time I press BT pairing button. I've only tried with Raspi4 onboard bluetooth, ESP32 BT proxy and ECO16BT a meter away. The Bluez errors are new to me, I haven't seen those ones before.

Which bluetooth adapter do you have? Does it pair other BLE devices nicely? Does it have many BLE devices connected simultaneously?

**Comment by Isusami** [comment]
I attempted to connect multiple times (about 10 times). 
Bluez may refer to the built-in Bluetooth adapter in my server. 
I do have another device that connects via Bluetooth smoothly.
If you need some debugs or more details I can provide them for troubleshooting this

**Comment by Isusami** [comment]
My Bluetooth device is `Intel Corporate 0033 (30:05:05:A6:36:09)`

**Comment by ExMacro** [comment]
Ok so the BT radio detects the Ensto thermostat and the integration sees that it in pairing mode. I usually got this kind of behavior in my tests when the bluetooth radio of my HA was on the edge of droppibg connection. Can you try with the HA BT radio being closer to the thermostat? 1-1.5m at first and then increase the distance from there.

**Comment by ExMacro** [comment]
Also, can you set the integration to debug mode to see a bit more debug info from the integration. Let's see if it gives us more information.

```
logger:
  default: info
  logs:
    custom_components.hass_ensto_ble: debug
```

**Comment by ExMacro** [comment]
@Isusami  I updated the integration code just to show device RSSI when pairing the device. It might help understanding the issue. I just tested my raspi 4 a meter away in a clear line of sight with the Ensto ECO16 BT and the RSSI was still about -70dBm, which is far from being excellent.

https://github.com/ExMacro/hass_ensto_ble/releases/tag/v0.3.9

**Comment by x53414D** [comment]
Thank you for your effort. This is my quick test for now:
ECO16BT bc3971 (14:2D:41:BC:39:71) [-82 dBm] – still failed.
I believe my antenna is positioned too low. I will test it again and move my server closer to the ECO16BT to see how it impacts the results.

**Comment by Isusami** [comment]
Thank you for your effort. This is my quick test for now:
ECO16BT bc3971 (14:2D:41:BC:39:71) [-82 dBm] – still failed.
I believe my antenna is positioned too low. I will test it again and move my server closer to the ECO16BT to see how it impacts the results.

**Comment by Isusami** [comment]
ECO16BT bc3971 (14:2D:41:BC:39:71) [-77 dBm]
Still failed
`
2025-03-19 20:40:18.193 DEBUG (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Finding device 14:2D:41:BC:39:71
2025-03-19 20:40:18.194 DEBUG (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Connecting to device 14:2D:41:BC:39:71
2025-03-19 20:40:18.998 DEBUG (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Connected to device 14:2D:41:BC:39:71
2025-03-19 20:40:18.998 DEBUG (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Pairing with device 14:2D:41:BC:39:71
2025-03-19 20:40:19.348 ERROR (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Failed to connect: [org.bluez.Error.AuthenticationFailed] Authentication Failed`

**Comment by Isusami** [comment]
Added more debugs command

```
2025-03-20 09:13:57.301 DEBUG (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Finding device 14:2D:41:BC:39:71
2025-03-20 09:13:57.301 DEBUG (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Connecting to device 14:2D:41:BC:39:71
2025-03-20 09:13:57.301 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Connecting to device @ 14:2D:41:BC:39:71
2025-03-20 09:13:57.304 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Connecting to BlueZ path /org/bluez/hci0/dev_14_2D_41_BC_39_71
2025-03-20 09:13:57.361 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_73_77_48_FE_2D_42): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -64)>}, []]
2025-03-20 09:13:57.361 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_30_13_8B_30_60_F5): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -84)>}, []]
2025-03-20 09:13:57.365 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_77_7B_2F_9F_78_E8): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -60)>}, []]
2025-03-20 09:13:57.378 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_79_66_CF_BD_B3_4F): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -60)>}, []]
2025-03-20 09:13:57.408 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_F7_1C_B1_B4_BD_D6): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -77)>}, []]
2025-03-20 09:13:57.420 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_44_84_84_87_89_1A): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -77)>}, []]
2025-03-20 09:13:57.446 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_5A_7E_E7_C1_EB_18): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -61)>}, []]
2025-03-20 09:13:57.469 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_5F_AA_90_B6_DF_6C): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -85)>}, []]
2025-03-20 09:13:57.543 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_73_77_48_FE_2D_42): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -85)>}, []]
2025-03-20 09:13:57.580 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_C4_D8_13_F6_84_79): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -57)>}, []]
2025-03-20 09:13:57.675 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_30_13_8B_30_60_F5): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -63)>}, []]
2025-03-20 09:13:57.682 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_EF_85_AF_21_1D_25): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -78)>}, []]
2025-03-20 09:13:57.683 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_44_84_84_87_89_1A): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -77)>}, []]
2025-03-20 09:13:57.727 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_5A_7E_E7_C1_EB_18): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -60)>}, []]
2025-03-20 09:13:57.735 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_73_77_48_FE_2D_42): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -64)>}, []]
2025-03-20 09:13:57.736 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_CC_37_30_39_70_BA): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -64)>}, []]
2025-03-20 09:13:57.762 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_79_66_CF_BD_B3_4F): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -61)>}, []]
2025-03-20 09:13:57.775 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_14_2D_41_BC_39_71): ['org.bluez.Device1', {'RSSI': <dbus_fast.signature.Variant ('n', -80)>}, []]
2025-03-20 09:13:58.581 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_14_2D_41_BC_39_71): ['org.bluez.Device1', {'Connected': <dbus_fast.signature.Variant ('b', True)>}, []]
2025-03-20 09:13:59.458 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_14_2D_41_BC_39_71): ['org.bluez.Device1', {'ServicesResolved': <dbus_fast.signature.Variant ('b', True)>}, []]
2025-03-20 09:13:59.459 DEBUG (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Connected to device 14:2D:41:BC:39:71
2025-03-20 09:13:59.459 DEBUG (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Pairing with device 14:2D:41:BC:39:71
2025-03-20 09:13:59.468 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Pairing to BLE device @ 14:2D:41:BC:39:71
2025-03-20 09:14:00.159 ERROR (MainThread) [custom_components.hass_ensto_ble.ensto_thermostat_manager] Failed to connect: [org.bluez.Error.AuthenticationFailed] Authentication Failed
2025-03-20 09:14:00.563 DEBUG (MainThread) [bleak.backends.bluezdbus.manager] received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_14_2D_41_BC_39_71): ['org.bluez.Device1', {'ServicesResolved': <dbus_fast.signature.Variant ('b', False)>, 'Connected': <dbus_fast.signature.Variant ('b', False)>}, []]
2025-03-20 09:14:00.564 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Device disconnected (/org/bluez/hci0/dev_14_2D_41_BC_39_71)
2025-03-20 09:14:00.564 DEBUG (MainThread) [bleak.backends.bluezdbus.client] _cleanup_all(/org/bluez/hci0/dev_14_2D_41_BC_39_71)
```

**Comment by ExMacro** [comment]
> Thank you for your effort. This is my quick test for now: ECO16BT bc3971 (14:2D:41:BC:39:71) [-82 dBm] – still failed. I believe my antenna is positioned too low. I will test it again and move my server closer to the ECO16BT to see how it impacts the results.

Hmm. That's quite bad reception if the Ensto thermostat is 1 meter away in clear sight. My ECO16BT and Raspi 4 built-in radio gives something like -70dBm. The connection becomes unstable in my tests when te RSSI value is dropping under -80dBm. Might work, might not. Quite similar behaviour to WLAN radios in that sense.

You seem to have quite many other BT devices that give better results. This seems to confirm the "badness" of the Ensto BLE radio, which we already knew.

You don't have multiple BLE devices connecting at the same time to your HA device do you? Most BT radios in Raspis etc. only allow between 3-5 active connections at the same time. So if there aren't any free "bluetooth slots" available, this might also cause problems. Haven't seen org.bluez.Error.AuthenticationFailed error in these cases though. That error is a bit different.

**Comment by ExMacro** [comment]
@Isusami You could also try this:

> My testtaspi SD card died and I had to reinstall. After reinstallation I couldn't connect to my thermostats anymore and they wouldn't pair. I got the same errors as you. Here's how I solved it:
> 
> go to HA terminal (OS version has it as an addon)
> start bluetoothctl (all the bluetooth stuff will go through the screen quickly..)
> write this to manually trust the device in terminal "trust 0C:43:14:8F:41:E6" -> replace with your thermostats Mac address
> write this to manually pair the device in terminal "pair 0C:43:14:8F:41:E6" -> replace with your thermostats Mac address
> type exit to exit from the bluetoothctl mode
> Try to pair the thermostat now after manually "trusting" the BLE device in HA OS Linux terminal. For me this did the trick. Let me know if it helps you and if it does, I have something to work on. This fix worked on my Raspberry Pi 4 with the built-in bluetooth radio and lates HA OS 15 etc.
> 
> You can also try bluetoothctl info 0C:43:14:8F:41:E6 (or your MAC) to get something like:
> 
> Device 0C:43:14:8F:41:E6 (public)
>         Name: ECO16BT 8f41e6
>         Alias: ECO16BT 8f41e6
>         Paired: yes
>         Bonded: yes
>         Trusted: yes
>         Blocked: no
>         Connected: yes
>         LegacyPairing: no
>         UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
>         UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
>         UUID: Vendor specific           (1d14d6ee-fd63-4fa1-bfa4-8f47b42119f0)
>         UUID: Vendor specific           (f49cefd5-209b-4531-99bd-123456789012)
>         UUID: Vendor specific           (f49cefd5-209b-4531-99bd-89fe2909931a)
>         ManufacturerData.Key: 0x2806 (10246)
>         ManufacturerData.Value:
>   45 43 4f 31 36 42 54 3b 31 3b 30 3b 30 3b 00 00  ECO16BT;1;0;0;..
>   00 00 00 00 00 00 00                             .......         
>         RSSI: 0xffffffc4 (-60)
>         AdvertisingFlags:

**Comment by back-2-95** [comment]
I stumbled on this repo and this issue from playing with https://github.com/jumakki/esphome-ensto.

I was able to get connection nicely with @jumakki 's codes.

With this I get the same problem as @Isusami - my bluetooth (proxy) is M5Stack Lite (esp32). Running latest HA on MacMini.
Bluetooth proxy is about 1m away but as I said, connection worked fine with jumakki's codes.

Thermo is ECO16BT and I have multiple of them.

I also tried unpairing thermo from Ensto app but to no luck with that either.

How can I see the reception so I could give my data?

**Comment by ExMacro** [comment]
@back-2-95 You can enable debug logging for HASS Ensto BLE integration by adding this to your configuration.yaml
```
logger:
  default: info
  logs:
    custom_components.ensto_ble: debug
```

**Comment by back-2-95** [comment]
Thx, now I get logs. And I found also a place from UI which shws RSSI values: 

![Image](https://github.com/user-attachments/assets/7b256b6c-1050-4902-87f1-1807455f1e89)

**Comment by ExMacro** [comment]
Thanks for the update @back-2-95 !

Did I understood correctly that you have four Ensto thermostats and are able to pair them but one of them (MAC A4:6D:D4:21:CB:27) doesn't pair? The RSSI -82 is the only one imho that might cause problems in terms of signal strength but it's with a different MAC address.

My own cheap esp32 boards can keep max. three BLE connections at the same time but I don't know about the specification of the M5 Atom lite. Currently my HASS Ensto integration doesn't really take this into account so with more than 1-2 thermostats this might become a problem if your HA needs to use BLE for other devices as well. Might cause drop outs from time to time since HA is trying to send many GATT commands at the same time.

**Comment by back-2-95** [comment]
I have only tried with `A4:6D:D4:21:CB:27` (it's the one nearest to my work desk). The one with RSSI -82 has most distance to my HA machine, not a lot but more interference between.

And currently either of my BLEs have other devices there.

Summary: Only that one Ensto and no other ble devices connected.

**Comment by ExMacro** [comment]
@back-2-95 Did you already try to manually trust the device from the terminal? Not sure if it helps but might.

```
Go to HA terminal (OS version has it as an addon)
start bluetoothctl (all the bluetooth stuff will go through the screen quickly..)
write this to manually trust the device in terminal "trust 0C:43:14:8F:41:E6" -> replace with your thermostats Mac address
write this to manually pair the device in terminal "pair 0C:43:14:8F:41:E6" -> replace with your thermostats Mac address
type exit to exit from the bluetoothctl mode
Try to pair the thermostat now after manually "trusting" the BLE device in HA OS Linux terminal. For me this did the trick. Let me know if it helps you and if it does, I have something to work on. This fix worked on my Raspberry Pi 4 with the built-in bluetooth radio and lates HA OS 15 etc.

You can also try bluetoothctl info 0C:43:14:8F:41:E6 (or your MAC) to get something like:

Device 0C:43:14:8F:41:E6 (public)
Name: ECO16BT 8f41e6
Alias: ECO16BT 8f41e6
Paired: yes
Bonded: yes
Trusted: yes
Blocked: no
Connected: yes
LegacyPairing: no
UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
UUID: Device Information (0000180a-0000-1000-8000-00805f9b34fb)
UUID: Vendor specific (1d14d6ee-fd63-4fa1-bfa4-8f47b42119f0)
UUID: Vendor specific (f49cefd5-209b-4531-99bd-123456789012)
UUID: Vendor specific (f49cefd5-209b-4531-99bd-89fe2909931a)
ManufacturerData.Key: 0x2806 (10246)
ManufacturerData.Value:
45 43 4f 31 36 42 54 3b 31 3b 30 3b 30 3b 00 00 ECO16BT;1;0;0;..
00 00 00 00 00 00 00 .......
RSSI: 0xffffffc4 (-60)
AdvertisingFlags:
```

**Comment by back-2-95** [comment]
This worked and I got that one Ensto added:

![Image](https://github.com/user-attachments/assets/b1080319-61ad-4282-a7e4-844cf10058b8)

**Comment by ExMacro** [comment]
Excellent! I have to investigate the Linux BLE pairing process further when I have the time. I'll wait for @Isusami comment before closing the issue.

**Comment by back-2-95** [comment]
Any new info on this issue? @Isusami @ExMacro

**Comment by Isusami** [comment]
Well yeah, I'm back from vacation and ordered new Bluetooth USB and waiting for delivery.
I suspect to my on onboard chip cannot communate with my sensor.

**Comment by ExMacro** [comment]
@Isusami Let us know how it goes.

**Comment by ExMacro** [comment]
Hmm. Did you already try this little test with bluetoothctl?

```
Go to HA terminal (OS version has it as an addon)
start bluetoothctl (all the bluetooth stuff will go through the screen quickly..)
write this to manually trust the device in terminal "trust 0C:43:14:8F:41:E6" -> replace with your thermostats Mac address
write this to manually pair the device in terminal "pair 0C:43:14:8F:41:E6" -> replace with your thermostats Mac address
type exit to exit from the bluetoothctl mode
Try to pair the thermostat now after manually "trusting" the BLE device in HA OS Linux terminal. For me this did the trick. Let me know if it helps you and if it does, I have something to work on. This fix worked on my Raspberry Pi 4 with the built-in bluetooth radio and lates HA OS 15 etc.

You can also try bluetoothctl info 0C:43:14:8F:41:E6 (or your MAC) to get something like:

Device 0C:43:14:8F:41:E6 (public)
Name: ECO16BT 8f41e6
Alias: ECO16BT 8f41e6
Paired: yes
Bonded: yes
Trusted: yes
Blocked: no
Connected: yes
LegacyPairing: no
UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
UUID: Device Information (0000180a-0000-1000-8000-00805f9b34fb)
UUID: Vendor specific (1d14d6ee-fd63-4fa1-bfa4-8f47b42119f0)
UUID: Vendor specific (f49cefd5-209b-4531-99bd-123456789012)
UUID: Vendor specific (f49cefd5-209b-4531-99bd-89fe2909931a)
ManufacturerData.Key: 0x2806 (10246)
ManufacturerData.Value:
45 43 4f 31 36 42 54 3b 31 3b 30 3b 30 3b 00 00 ECO16BT;1;0;0;..
00 00 00 00 00 00 00 .......
RSSI: 0xffffffc4 (-60)
AdvertisingFlags:
```

**Comment by Isusami** [comment]
I think I have done this before, but I will test it today and post the result.

**Comment by back-2-95** [comment]
I just added another thermosthat yday. I failed few times but this was the "order of things" to get it working:

1. in terminal, run `bluetoothctl` and bluetooth stuff starts to print to the screen...
2. while it does, I can run commands. I run first `trust 0C:43:14:8F:41:E6` (with my mac address)
3. then `pair 0C:43:14:8F:41:E6`
4. set termosthat to pairing mode (blue light blinking)
5. Go to Add integration modal, search for "Ensto" - it should list the Mac address of your thermostat (btw this can be used to find out mac addresses for devices)
6. Add it successfully

**Comment by Isusami** [comment]
Yay, finally it works.
I follow this guide, it works withthe  first attempt
```
in terminal, run bluetoothctl and bluetooth stuff starts to print to the screen...
while it does, I can run commands. I run first trust 0C:43:14:8F:41:E6 (with my mac address)
then pair 0C:43:14:8F:41:E6
set termosthat to pairing mode (blue light blinking)
Go to Add integration modal, search for "Ensto" - it should list the Mac address of your thermostat (btw this can be used to find out mac addresses for devices)
Add it successfully
```

Thanks for all the help.
@back-2-95 @ExMacro

**Comment by ExMacro** [comment]
Excellent! I will update this into the readme as a backup solution for now if the normal pairing doesn't work. Seems to be related to how Linux handles bluetooth pairing so this could possibly be fixed in a future release. I'm not a professional programmer so let's see how big of a challenge it is..

Thanks for your help debugging @back-2-95

**Comment by Isusami** [comment]
Hey @ExMacro, 

I'm back with a solution! I experimented with various scenarios using different Bluetooth hardware, and I finally figured out the cause of the error. Here are the key points:

1. Bluetooth coverage can affect connectivity.
2. The file `/homeassistant/.storage/ensto_ble_devices` is not being removed. When you add the device again, this file still exists. Since the "factory_reset_id" changes each time you add a new device, this can cause issues.

_So my solution was removing the ensto_ble_devices and adding them again, and it works. Maybe by checking this file before adding a new device, we can prevent this kind of behavior._

Let me know if this helps!

**Comment by ExMacro** [comment]
Thanks @Isusami for debugging! I will try it out next week.

**Comment by Isusami** [comment]
I'm unsure about `terminal -> remove -> trust -> pair -> re-add `, it can remove the device from _ensto_ble_devices_.
Now, you were right. My commit is not working, but when I remove this file, I can easily add the device again, and I don't even do the step you mentioned. Something weird may be happening with the Docker setup.
And I have to mention that ESP32 and Ensto should be so close to each other that they can pair; otherwise, they won't. For my setup, the distance was about 1 meter and ~50db.
